[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
board = { path = "../board" }
clap = { version = "4.5.28", features = ["derive"] }
evaluation = { path = "../evaluation" }
rayon = "1.10.0"
